services:
    todolist_web:
        container_name: todolist_web
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "80:80"  # Map port 8080 on the htodolistt to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - todolist_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - todolist-network  # Connect to the custom network

    todolist_app:
        container_name: todolist_app
        build: .  # Build from the Dockerfile
        depends_on:
            - todolist_db
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
        networks:
            - todolist-network  # Connect to the custom network

    todolist_db:
        container_name: todolist_db
        image: mysql:8  # Use MySQL image
        restart: unless-stopped
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: laravel_vuejs_todolist  # Create a database named 'laravel'
            MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
        volumes:
            - todolist_db:/var/lib/mysql  # Persist MySQL data
        networks:
            - todolist-network  # Connect to the custom network
# Define the custom network
networks:
    todolist-network:  # Create a custom network named 'todolist-network'
        driver: bridge

# Define the volume for MySQL data persistence
volumes:
    todolist_db:
